// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR5NX3JbZuxHj3eo6DQVtrbMR1GR1HQiA',
    appId: '1:120736210659:web:db15c91b8181ad68f76fd6',
    messagingSenderId: '120736210659',
    projectId: 'semesterproject-fe671',
    authDomain: 'semesterproject-fe671.firebaseapp.com',
    databaseURL: 'https://semesterproject-fe671-default-rtdb.firebaseio.com',
    storageBucket: 'semesterproject-fe671.firebasestorage.app',
    measurementId: 'G-KTTE73KD2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzOUY80AnEBNaq-EJi4AqDvk38RQKf_f8',
    appId: '1:120736210659:android:1f74e02444cc23f1f76fd6',
    messagingSenderId: '120736210659',
    projectId: 'semesterproject-fe671',
    storageBucket: 'semesterproject-fe671.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQQamsiElbTiaeh3W0kcTmT6PbvCbm6GE',
    appId: '1:120736210659:ios:e2d5468e24548871f76fd6',
    messagingSenderId: '120736210659',
    projectId: 'semesterproject-fe671',
    databaseURL: 'https://semesterproject-fe671-default-rtdb.firebaseio.com',
    storageBucket: 'semesterproject-fe671.firebasestorage.app',
    iosBundleId: 'com.example.semesterproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR5NX3JbZuxHj3eo6DQVtrbMR1GR1HQiA',
    appId: '1:120736210659:web:97da307dcf24a569f76fd6',
    messagingSenderId: '120736210659',
    projectId: 'semesterproject-fe671',
    authDomain: 'semesterproject-fe671.firebaseapp.com',
    databaseURL: 'https://semesterproject-fe671-default-rtdb.firebaseio.com',
    storageBucket: 'semesterproject-fe671.firebasestorage.app',
    measurementId: 'G-CZ2LDE9YM6',
  );
}
